name: Post to Gitea wiki
description: 🚀 Gitea Action to publish files to a Gitea wiki

inputs:
  filepath:
    description:
      Path of the folder containing the wiki files to be deployed
      Defaults to the wiki/ folder
    default: wiki

  userName:
    description:
      Git user name of commit
    default: wiki.bot

  userEmail:
    description:
      Git user email of commit
    default: wiki.bot@noreply.com

  commitMessage:
    description:
      Git commit message
    default: Publish wiki

outputs:
  wikiUrl:
    description:
      URL of the published Gitea wiki
    value: ${{ steps.main.outputs.wikiUrl }}

runs:
  using: composite
  steps:
    - id: post
      shell: bash
      run: bash "$GITHUB_ACTION_PATH/post-wiki.sh"
      env:
        INPUT_GITEA_SERVER_URL: ${{ github.server_url }}
        INPUT_REPOSITORY: ${{ gitea.repository }}
        INPUT_FILEPATH: ${{ inputs.filepath }}
        INPUT_GIT_USER_NAME: ${{ inputs.userName }}
        INPUT_GIT_USER_EMAIL: ${{ inputs.userEmail }}
        INPUT_GIT_COMMIT_MSG: ${{ inputs.commitMessage }}
        INPUT_TOKEN: ${{ github.token }}
