name: Post to Gitea wiki
description: 🚀 Gitea Action to publish files to a Gitea wiki

inputs:
  wikiPath:
    description:
      Path of the folder containing the wiki files to be deployed
    default: wiki

  userName:
    description:
      Git user name of wiki commit
    default: wiki.bot

  userEmail:
    description:
      Git user email of wiki commit
    default: wiki.bot@noreply.com

  commitMessage:
    description:
      Wiki repository commit message
    default: Auto Publish Wiki

  removeHistory:
    description: 
      Remove wiki history
    default: 'false'

outputs:
  wikiUrl:
    description:
      URL of the repository wiki
    value: ${{ steps.main.outputs.wikiUrl }}

runs:
  using: composite
  steps:
    - id: post
      shell: bash
      run: bash "$GITHUB_ACTION_PATH/post-wiki.sh"
      env:
        INPUT_GITEA_SERVER_URL: ${{ github.server_url }}
        INPUT_REPOSITORY: ${{ gitea.repository }}
        INPUT_WIKI_PATH: ${{ inputs.wikiPath }}
        INPUT_GIT_USER_NAME: ${{ inputs.userName }}
        INPUT_GIT_USER_EMAIL: ${{ inputs.userEmail }}
        INPUT_GIT_COMMIT_MSG: ${{ inputs.commitMessage }}
        INPUT_REMOVE_HISTORY: ${{ inputs.removeHistory }}
        INPUT_TOKEN: ${{ github.token }}
