name: Release and post own wiki
on:
  push:
    branches: "main"
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    paths-ignore:
      - wiki/**
      - LICENSE
      - README.md

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action code
        uses: actions/checkout@v3

      - name: Invoke default action
        id: postWiki
        uses: ./

      - name: Verify wiki url
        shell: bash
        run: '[[ $OUTPUT_WIKI_URL == ${{ github.server_url }}/${{ gitea.repository }}/wiki ]]'
        env:
          OUTPUT_WIKI_URL: ${{ steps.postWiki.outputs.wikiUrl }}